---
title: "git_00"
author: "Kevin Lindo"
date: "Summer 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->
’Twas brillig, and the slithy toves
      Did gyre and gimble in the wabe:
All mimsy were the borogoves,
      And the mome raths outgrabe.

“Beware the Jabberwock, my son!

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
Two roads diverged in a yellow wood,
And sorry I could not travel both
And be one traveler, long I stood
And looked down one as far as I could
To where it bent in the undergrowth

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
The sun was shining on the sea,
      Shining with all his might
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
When I get bigger, big enough to go somewhere by myself.

I want to go to a land that's far away.

I want to go to a faraway island.

I want to go to an island that has no people.

I want to go to an island that has no pain or sadness.

There are no adults, children, classmates, teachers or my mom on that island.

On that island, I can climb a tree when I want to climb.

swim in the sea when I want to swim.

and sleep when I want to sleep.

On that island, I think about the town that I left behind.

Kids go to school, as if nothing has changed.

Adults go to office as if nothing has changed.

Mom eats, as if nothing has changed.

When I thing about the town without me, I feel a sense of relief.

I want to go far, far away.